### ISSUE TITLE
Tokenization of clitics

### ISSUE THREAD

**Issue by ceramisch** [UniversalDependencies/UD_Portuguese-GSD#10]
Reflexive clitics such as _se_ sometimes attach to the verb, like in sentence train-s61:

_O qualificativo de "pessoal" refere - se ao fato ..._

This treebank tokenizes this as three tokens, _refere_, _-_ (hyphen alone) and _se_.

I suggest either adding SpaceAfter=No to the first and second tokens, or to use the same technique as in Bosque, that is, treat it as a contraction with ranges:

```
X-X+1 refere-se
X refere
X+1 se
```

For more homogeneity among treebanks, I prefer treating it as a contraction with ranges.

**Comment by dan-zeman** [comment]
It is definitely preferred that this is done the same way in all Portuguese treebanks.

**Comment by arademaker** [comment]
Yes @ceramisch let us make it following bosque approach

**Comment by ceramisch** [comment]
I am working on GSD for PARSEME and discovered that this issue was still pending.

I'll try to work on homogenizing it after the PARSEME rush is over.

Do you have any suggestion for an editor which, when I remove one token, will adapt all HEAD to the new IDs shifted by one after the removed token? This concerns the suppression of the hyphen in these clitic+verb combinations, since the hyphen is not present in Bosque either.

**Comment by martinpopel** [comment]
One such framework is [Udapi](http://udapi.github.io). BTW: It was used to convert GSD to UD (and UDv1 to UDv2). See [the ud.pt.AddMwt block](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/pt/addmwt.py) for inspiration.

**Comment by arademaker** [comment]
@Cristiananc can you try solve this? Let us talk about.

**Comment by arademaker** [comment]
@AngledLuffa commented in #7 

> Another idea would be to just train a model without the broken sentences, then give the model a chance to redo the dependencies in a hopefully better manner for those sentences

Indeed, I was thinking for a while about using the model trained with UD_Portuguese-Bosque to parse UD_Portuguese-GSD and try to identify patterns to be fixed. This issue makes things more complicated since tokenization of sentences would differ. So instead of addressing #7 first, what do you think about trying some automation to fix this issue here? 

GSD contains many cases of erroneous tokenization

```
% grep "text =" *.conllu | grep -h --color -o -E "([^ ]+ \- (lhes?|me|se|nós|vós|os?|as?)[ ])"  | sort | uniq -c | sort -nr | head -20
  16 tornou - se
  14 Estende - se
   8 encontra - se
   7 Trata - se
   5 referindo - se
   4 tornar - se
   4 localiza - se
   4 encontram - se
   4 destacam - se
   3 tornando - se
   3 tornam - se
   3 refere - se
   3 pode - se
   3 mudou - se
   3 destaca - se
   3 Pode - se
   2 trata - se
   2 tornando - o
   2 torna - se
   2 tendo - se
```

```
4       tornou  tornar  AUX     AUX     _       7       cop     _       _
5       -       -       PUNCT   .       _       7       punct   _       _
6       se      _       PART    PRT     _       7       expl:pv _       _
7       pesquisador     pesquisador     NOUN    NOUN    _       0       root    _       _
```

versus bosque

```
% grep "text =" ~/work/ud-portuguese-bosque/documents/*.conllu | grep -h --color -o -E "([^ ]+\-(lhes?|me|se|nós|vós|os?|as?)[ ])"  | sort | uniq -c | sort -nr | head
  14 encontra-se
  12 Trata-se
   8 trata-se
   7 deve-se
   6 tornou-se
   5 Recorde-se
   4 tornar-se
   4 tem-se
   4 reunir-se
   4 referindo-se
```

```
3-4     tornou-se       _       _       _       _       _       _       _       _
3       tornou  tornar  VERB    <mv>|<hyphen>|<se-passive>|V|PS|3S|IND|@FS-STA  Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin  0       root    _       _
4       se      se      PRON    PERS|F|3S|ACC|@<ACC-PASS        Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs          3       expl    _       _
5       local   local   NOUN    <np-idf>|N|M|S|@<OC     Gender=Masc|Number=Sing 3       xcomp   _       _
```

To fix:

1. we need to fix the tokenization in the `text` metadata.. 
2. we need to create the MWT token with the `VERB-PRON`
3. we need to remove the token `-` and adjust the rest of the token ids
4. we need to make the pronoun a and `expl` child of the preceding VERB
5. we need to decide what to do with the children of the PRON or VERB
6. we need to add features to the PRON and VERB tokens. But we can postpone that one. I do have other ways to do it.

See 273214d

**Comment by AngledLuffa** [comment]
#1, #2, #3 are easy.  I'm not sure what you mean by #5 - the structure of
the sentence doesn't change in any way, does it?  For #4, do you mean in
cases where the pronoun is not already a child of the preceding VERB?

It is worth pointing out that the xpos was lost on word 18 (PRON) in the
change you linked.

I was able to find some examples of "VERB - clitic" which don't appear in
your grep.  For example:

# sent_id = dev-s226
16      desenvolve      desenvolver     VERB    VERB    _       4
conj    _       _
17      -       -       PUNCT   .       _       16      punct   _       _
18      se      _       PART    PRT     _       16      expl:pv _       _

but desenvolve wasn't part of your list.  Would this also change, or do I
need to exclude these?

**Comment by AngledLuffa** [comment]
Ah, I see the "head -n 20" - looks like this example was missing just on
account of that

**Comment by arademaker** [comment]
Hi @martinpopel! Yes, I know about your tool. I must confess that I forgot how to use these blocks but notice that the problem here is not only the contractions but the clitics. pronouns attached to verbs.

**Comment by AngledLuffa** [comment]
Actually this change is perfect for an addition I wanted to make to
Stanford's dependency graph manipulation tool.  It already had the ability
to mark the words as MWT, but I just added a one line command which removes
an unwanted leaf and renumbers the rest of the words and dependency edges.
I put the results in a PR:

https://github.com/UniversalDependencies/UD_Portuguese-GSD/pull/37

I don't know anything about the workbench software, although it would also
be reasonable to run the same script on each of those individual files if
that would be a preferable approach.

**Comment by arademaker** [comment]
workbench is the name of the `branch` in this repo I used to maintain the data. I will move it to `dev` as soon as possible. But for now, I work in the workbench branch and from time to time, run a script to produce the dev/train/test files and copy them to the dev branch.

**Comment by arademaker** [comment]
I closed the PR, yes, sorry, I need PR to the workbench, in the files under `documents` folder. Those are the real SOURCE data in this repo.... as I said above... for now.

**Comment by martinpopel** [comment]
> I know about your tool. 

Now, I see this is an old issue and was advertising Udapi already three years ago.

> I must confess that I forgot how to use these blocks

simply: `udapy -s ud.pt.AddMwt < in.conllu > out.conllu`

> but notice that the problem here is not only the contractions but the clitics. pronouns attached to verbs.

I see. So `ud.pt.AddMwt` is not suitable for this - it converted a single word into a single MWT. Now there are three words ("refere - se") which should be converted into a single MWT ("refere-se") with two words ("refere se").
Something like this could work (not tested!):

```python
udapy -s util.Eval node='
if node.form == "-":
  verb, clitic = node.prev_node, node.next_node
  if verb.upos == "VERB" and clitic.upos in ("PRON", "PART") and clitic.form.lower() in "lhe lhes me se nos vos o os a as".split():
    node.remove()
    verb.root.create_multiword_token([verb, clitic], verb.form + "-" + clitic.form)
    verb.root.text = None
' < in.conllu > out.conllu
```
The `verb.root.text = None` forces Udapi to recompute the `text` CoNLL-U comment.

**Comment by AngledLuffa** [comment]
Heh, now I'm feeling envious of the generalizable script creating in Udapi.  Nice.

Anyway, I reran my script and recreated the MWT branch

**Comment by arademaker** [comment]
We still have

```
% grep "text =" *.conllu | grep -h --color -o -E "([^ ]+ \- (lhes?|me|se|nós|vós|os?|as?)[ ])"  | sort | uniq -c | sort -nr | head -20
  12 tornou - se
   3 pode - se
   3 Pode - se
   2 tornar - se
   2 tendo - se
   2 deve - se
   2 designar - se
   2 Tornou - se
   2 Deve - se
   1 sagrou - se
   1 intitular - se
   1 foi - lhe
   1 fez - se
   1 elegeu - se
   1 domingo - os
   1 Ver - o
   1 "ofereça - a
```

**Comment by AngledLuffa** [comment]
Those were tagged AUX, which I had not touched.  I can go back and do those
as well.
