### ISSUE TITLE
Validation error leaf-aux-cop

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_Portuguese-GSD#31]
in folder https://github.com/UniversalDependencies/UD_Portuguese-GSD/tree/workbench/reports we have leaf-aux-cop errors, they can be found using:

```
$ grep 'L3 Syntax leaf-aux-cop' *.report
pt_gsd-ud-train-0332.report:[Line 25 Sent train-s3292 Node 20]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (20:tendo:aux --> 22:se:expl)
pt_gsd-ud-train-0718.report:[Line 234 Sent train-s7132 Node 6]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (6:tem:aux --> 7:mais:advmod)
```

**Comment by arademaker** [comment]
Podemos começar com uma correção em lote. No bosque tendo-se é analisado como um MWT, e os tokens relacionados são "tendo" e "se". Vc consegue pensar em um script para tornar o GSD como o bosque? Quais casos de análise (dependência e head) temos no bosque? Sempre a mesma ou temos variações? Podemos capturar os casos?
