### ISSUE TITLE
Are there any plans to fix the remaining errors for UD 2.12?

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/UD_Portuguese-GSD#36]
I am asking because this treebank is in the NEGLECTED status and validation exceptions for most error types in it have expired. The data freeze deadline is one month from now and if the errors are not fixed, the treebank will unfortunately have to be dropped from UD.

**Comment by arademaker** [comment]
Yes, I do have plans to fix the errors

**Comment by arademaker** [comment]
Let me see what I can do in one moth. I will try to fix the most critical ones if possible

**Comment by AngledLuffa** [comment]
I have been working on a script which helps automate repetitive dependency edits (ssurgeon, now in CoreNLP and Stanza).  If you can explain how to generalize a few of the fixes, I can use a test case such as this treebank to make sure this script is working by running the edits on the whole treebank at once.

**Comment by dan-zeman** [comment]
For other treebanks, I would probably help with some automated fixes too, either via PRs towards dev, or directly in the dev branch. But here there is the workbench branch with workflow I don't understand (the original files seem to be split into smaller ones, people commit fixes there but there is never any merge into dev), so I thought I'd better not touch it now.

**Comment by arademaker** [comment]
Hi @AngledLuffa, let me check tomorrow if I can remember the two most common sources of errors. I do have the logs of the validation.py and some open issues.

@dan-zeman, I adopted the `workbench` branch as the working area for Portuguese-GSD and Portuguese-Bosque. Data is split into smaller files that can be opened in the text editor. I have scripts to merge the small files into the dev/test/train sets into the `dev` branch.  The `workbench` branch and the `dev/main` are disconnected, they do not have same structure or history. It is an alternative to the [not-to-release](https://github.com/UniversalDependencies/UD_English-EWT/tree/master/not-to-release) folder.

**Comment by dan-zeman** [comment]
> I adopted the `workbench` branch as the working area for Portuguese-GSD and Portuguese-Bosque. Data is split into smaller files that can be opened in the text editor. I have scripts to merge the small files into the dev/test/train sets into the `dev` branch. The `workbench` branch and the `dev/main` are disconnected, they do not have same structure or history. It is an alternative to the [not-to-release](https://github.com/UniversalDependencies/UD_English-EWT/tree/master/not-to-release) folder.

Aren't you worried that the `workbench` commits (and thus their authors) will have zero visibility in the `dev` and `master` branches? I thought this was a priority for you. Also, if you don't immediately propagate the changes from `workbench` to `dev`, the [validation page](http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Portuguese-GSD) may not reflect the real state of the treebank.

But all that are unimportant details if the main goal is reached: save the treebank for 2.12 :-)

**Comment by arademaker** [comment]
@dan-zeman, moving the working area to a subfolder in the dev branch can make my workflow more manageable, you are right. Let me consider that after the next release.  But since you are the only one that commits to the master, the visibility of the contributors is already very limited. 

https://github.com/UniversalDependencies/UD_Portuguese-GSD/graphs/contributors

I don't know how to see the contributors in a branch different from the master. Indeed, that is a priority for me. But since the dev is not visible, I was not missing anything with the workbench. But please tell me if I am missing something! ;-)

Regarding the validation reflecting the current stage... this is a really good point. 

Can you remember me what are the critical errors I need to fix in order to have Portuguese-GSD not removed from the 2.12?

**Comment by arademaker** [comment]
@AngledLuffa I updated the https://github.com/UniversalDependencies/UD_Portuguese-GSD/milestone/2 to group issues that I believe would be the priority.. Not sure what your approach can handle. If you want, we can schedule a call.

**Comment by dan-zeman** [comment]
> But since the dev is not visible, I was not missing anything with the workbench. But please tell me if I am missing something! ;-)

Yes, you are :-) we've been discussing this (at Bosque I think?) Whenever dev is merged to master, the commits in dev become part of history of master and people who contributed to dev become visible among contributors to master. Otherwise the link you posted would not show you and @ceramisch, it would be only me there. Technically you wouldn't have to abandon workbench to have the other people included there, but you would have to merge it regularly into dev (rather than just copying the resulting files), meaning that the small files would have to be in not-to-release even in workbench, which would probably make workbench pointless.

> Can you remember me what are the critical errors I need to fix in order to have Portuguese-GSD not removed from the 2.12?

Now that the old validation exceptions have expired, it is more or less everything that the validator reports. I think that the only exception is the 14 instances of "too-many-subjects", so you may want to leave this as the last step.

**Comment by arademaker** [comment]
Oh, you are right! Sorry, now I remember, since master and dev share history... the contributors from dev indeed appear in the statistics.

Not sure if I will be able to make... l will try my best.

**Comment by AngledLuffa** [comment]
How are we in terms of picking up this issue again?

**Comment by arademaker** [comment]
Give me one week, I will resume this thread

**Comment by ceramisch** [comment]
@arademaker If there's anything I can do to help, please don't hesitate to drop me a line. I'm interested in restoring Portuguese-GSD because we've annotated it in PARSEME, and it would be a pity to have a richly MWE-annotated corpus on top of a RETIRED treebank.

**Comment by arademaker** [comment]
Sure, my plan is to have GSD back to the next UD release

**Comment by arademaker** [comment]
Commit 23e360a solves almost all errors. The code is `not-to-release/scripts/issue-36.lisp`. Considering that we had ~11% of the corpus invalid, the only possible alternative was to submit the sentences to UDPipe asking for new analysis based on the newest `portuguese-bosque-ud-2.12-230717` model.

I reduced the number of sentences with errors to 123, which I will need to check manually. The new analyses were properly tagged (with sentence metadata) so we can revise these cases in the future.

**Comment by arademaker** [comment]
@dan-zeman , I don't see updates in the https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl report for this treebank, is it normal?

**Comment by dan-zeman** [comment]
> @dan-zeman , I don't see updates in the https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl report for this treebank, is it normal?

https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Portuguese-GSD says that the report was last updated yesterday, so I suppose it works (also, there are now only 100 errors, I think previously you had much more).

**Comment by arademaker** [comment]
Last commit fixed this issue.
