### ISSUE TITLE
Rename treebank

### ISSUE THREAD

**Issue by ceramisch** [UniversalDependencies/UD_Portuguese-GSD#4]
In accordance with other languages, this treebank should be renamed to UD_Portuguese-GSD or UD_Portuguese-BR-GSD

I'm not sure the variant code BR should be kept because it's not specified in other treebanks such as Bosque - By the way, it would be good to mention "Brazilian" "European" or both in the little description text that appears in the main UD table on the UD home page for all Portuguese treebanks.

**Comment by arademaker** [comment]
The https://github.com/UniversalDependencies/UD_Portuguese-Bosque treebank contains both Brazilian and Portuguese variations so I would suggest rename this treebank to UD_Portuguese-GSD. @dan-zeman? After release 2.2, I would like to see if we can start to contribute to this treebank too.

**Comment by ceramisch** [comment]
I'm interested in contributing too :-)

**Comment by dan-zeman** [comment]
I agree with the renaming and will take care of it. The BR suffix does not say that we insist on encoding language variants in the repo names; it just means that this treebank is the only one in the GSD family, that was not the first UD treebank of its language.

Good idea to put "European" or "Brazilian" or both to the title page. It will appear there after the next release if it is mentioned in the README in section `# Summary`.

**Comment by dan-zeman** [comment]
Renamed the repository and added @ceramisch as a contributor in the README. Let me know if you want your e-mail address to appear there as contact instead of mine.

**Comment by ceramisch** [comment]
> Good idea to put "European" or "Brazilian" or both to the title page. It will appear there after the next release if it is mentioned in the README in section # Summary

I just pushed a modification of the README.md in the dev branch of UD_Portuguese-Bosque to specify that the corpus contains both European and Brazilian. This is my first commit to an UD treebank, I hope I did it right :-)

**Comment by dan-zeman** [comment]
@arademaker, are you willing to be the contact person of UD_Portuguese-GSD?

**Comment by arademaker** [comment]
@dan-zeman, yes sure.

**Comment by dan-zeman** [comment]
Thanks! README modified. It's yours, guys :-)

**Comment by arademaker** [comment]
@dan-zeman, do you remember what GSD stands for?

**Comment by jnivre** [comment]
Google Stanford Dependencies

**Comment by arademaker** [comment]
Thank you
