### ISSUE TITLE
validation error: L3 Syntax leaf-mark-case

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/UD_Portuguese-GSD#7]
I can't do it for release 2.2, but I can help for the next release:

```
$ cat ../UD_Portuguese-GSD/pt_gsd-ud-*.conllu |  python2.7 validate.py --lang pt
[Line                   76]: Unknown UD DEPREL: xcomp:adj
[Line                   110]: Unknown UD DEPREL: xcomp:adj
[Line                   164]: Unknown UD DEPREL: xcomp:adj
[Line                   166]: Unknown UD DEPREL: det:poss
[Line                   299]: Unknown UD DEPREL: acl:part
[Line                   329]: Unknown UD DEPREL: xcomp:adj
[Line                   416]: Unknown UD DEPREL: acl:part
[Line                   509]: Unknown UD DEPREL: det:poss
[Line                   530]: Unknown UD DEPREL: xcomp:adj
[Line                   536]: Unknown UD DEPREL: xcomp:adj
[Line                   574]: Unknown UD DEPREL: xcomp:adj
[Line                   608]: Unknown UD DEPREL: det:poss
[Line                   630]: Unknown UD DEPREL: acl:part
[Line                   653]: Unknown UD DEPREL: acl:part
[Line                   675]: Unknown UD DEPREL: acl:part
[Line                   854]: Unknown UD DEPREL: acl:part
[Line                   863]: Unknown UD DEPREL: expl:pv
[Line                   867]: Unknown UD DEPREL: det:poss
[Line                   881]: Unknown UD DEPREL: det:poss
...suppressing further errors regarding Syntax
*** FAILED *** with 6987 errors
Syntax errors: 6987
```

**Comment by martinpopel** [comment]
I think it would be pity to omit a treebank from UD 2.2 just because of extra deprel subtypes.
The simplest solution is to include these in https://github.com/UniversalDependencies/tools/blob/master/data/deprel.pt and for the next release (UD 2.3) make sure all PT treebanks agree on what are the Portuguese-specific deprel subtypes and use them consistently.

**Comment by arademaker** [comment]
All right, I can try this latter today . Hope errors are only related to the extra deprel subtypes

**Comment by arademaker** [comment]
Anyway , we also have think if it makes sense to release a treebank with the kind of errors reported in #5 by @ceramisch

**Comment by dan-zeman** [comment]
I think it will be better to leave this corpus out of the shared task. The participants will have enough on their plate even without it, and its inconsistency with Bosque worries me. However, it can still be in the full release 2.2 after the shared task. Then the deadline is June 15.

**Comment by AngledLuffa** [comment]
For the first one, the sentence is

Nós do PSOL resolvemos expulsá - lo por causa da relação política dele com
o Deco ...

Is this "por causa da relação política dele com o Deco" not supposed to be
one complete phrase?  The dependency edit leaves them separated.

The first automated approach I had in mind involved coming up with a
generalization of the error type and deterministically rearranging the
dependencies to fix the errors.  It would require some idea of how to
reattach the dependencies that were previously wrong.  For example, in
"da relação", would we always expect "de a" to point to "relação"?  If so,
that would be easy enough to do.

What about "por causa"?  Should the "por" always point to "causa" instead
of the other way around, or will we find situations where that is not
true?  The issue there would be where and how to reattach the dependency,
such as if "causa" usually has a "obl" dependency and we just point it to
whatever "por" was originally pointing to.

Another idea would be to just train a model without the broken sentences,
then give the model a chance to redo the dependencies in a hopefully better
manner for those sentences

**Comment by arademaker** [comment]
related to #36, closed.
