### ISSUE TITLE
Contractions no, na, nos etc contain 'en' instead of 'em'

### ISSUE THREAD

**Issue by ceramisch** [UniversalDependencies/UD_Portuguese-GSD#9]
This one is easy to correct automatically:
All contractions of preposition _em_ + {o,a,os,as} = _n{o,a,os,as}_ are wrongly tokenized as _en_, with N and not M.
Do you see any problem in automatically modifying the tokens?

**Comment by arademaker** [comment]
No , go do it ! :-)

**Comment by ceramisch** [comment]
Solved in commit 469afb3

**Comment by arademaker** [comment]
Cases of `em` are not consistently annotated (deprel):

```
% awk '$2 ~ /^[Ee]m$/ {print $2,$3,$4,$8}' pt_gsd-ud-*.conllu | sort | uniq -c
 374 Em _ ADP case
   5 Em _ ADP mark
   2 Em _ PROPN case
 627 Em em ADP case
   6 em _ ADP advmod
3295 em _ ADP case
   5 em _ ADP dep
   1 em _ ADP fixed
 100 em _ ADP mark
   4 em _ ADP nmod
   1 em _ ADV advmod
5365 em em ADP case
```

I will work on that in the `dev` branch.

**Comment by ceramisch** [comment]
@arademaker This is a different issue, concerning the dependencies, and not the lemmas, right? Wouldn't it be better to close this issue and open a new one for the problem with inconsistent dependencies for this ADP? I can help fixing it, as soon as the PARSEME shared task is over.

**Comment by arademaker** [comment]
This is one more possible issue @Cristiananc ...

**Comment by arademaker** [comment]
@ceramisch was right in that the error with `em` I reported above is a different issue. But we had in the corpus many contractions not yet converted to MWT. Following the suggestion from @martinpopel in #20, I executed:

```
for f in *.conllu; do fn=$(basename $f .conllu); echo $f; udapy -s ud.pt.AddMwt < $f > $fn.tmp; mv $fn.tmp $f; done
```

Commit c0c25ff. Some validation errors were solved and some new ones appear, but it is as expected.

**Comment by arademaker** [comment]
I reverted last commit since the udapi code has bugs. `no/nos` as a pronoun is not a contraction.
